### ISSUE TITLE
img crop, the same as APBSN?

### ISSUE THREAD

**Issue by kaiq663** [p1y2z3/SDAP#1]
I follow the data preparation done by APBSN in which the patch size is 512 and the overlap size is 128, is that right?

**Comment by p1y2z3** [comment]
Of course you can. However, the repetition of each image ([self.repeat](https://github.com/p1y2z3/SDAP/blob/0f26896e7fe93e6dc2e95ba0ff464a38bfbd35f9/utils/loader.py#L58)) is set based on the quantity of the original images. If you choose to crop the original images, remember to adjust it accordingly. (If you don't adjust it, it's fine, but the number of iterations per epoch will increase, leading to longer training time.)
