### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by zhanzhanblue** [p1y2z3/SDAP#4]
你好，我想问一下实验结果里面的 (), (S), (E), (S, E) ,指的是什么呢，我读完不是很明白，感谢解答。

**Comment by zhanzhanblue** [comment]
是指一个数据集分成train和test吗

**Comment by p1y2z3** [comment]
S表示在训练的时候将测试集图片也加入训练集训练（因为是自监督，把噪声图片丢进去就行了）。E表示测试增强策略，本质上就是在测试的时候去两遍噪

**Comment by zhanzhanblue** [comment]
那这样的话，是不是dndbenchMark也放入了sidd mediem dataset中了呢。

**Comment by p1y2z3** [comment]
是的，混着训

**Comment by zhanzhanblue** [comment]
明白了，多谢多谢!!☆⌒(*＾-゜)v

**Comment by YiwenShan** [comment]
请问作者：SDAP(S)的训练集 究竟有没有SIDD Medium本身？

因为您在论文中的表述：4.4节 “we train our method on three test datasets in self-supervised manner, respectively”。最后的"respectively"给我的感觉是：只在SDAP在SIDD validation上训，在SIDD validation上测；(2) 只在SIDD benchmark上 重新训，SIDD benchmark上测；(3) 只在DND上 重新训，DND上测。就是训3个模型，分别在3个测试集上测。

但您在上面的回答 好像是说 SDAP(S)是在“SIDD Medium + SIDD validation + SIDD benchmark + DND benchmark”合并成的数据集上训1个模型，在3个测试集上测。

请问具体上怎么实操的呢？

**Comment by YiwenShan** [comment]
请问作者：SDAP(S)的训练集 究竟有没有SIDD Medium本身？

因为您在论文中的表述：4.4节 “we train our method on three test datasets in self-supervised manner, respectively”。最后的"respectively"给我的感觉是：只在SIDD validation上训，在SIDD validation上测；(2) 只在SIDD benchmark上 重新训，SIDD benchmark上测；(3) 只在DND上 重新训，DND上测。就是训3个模型，分别在3个测试集上测。

但您在上面的回答 好像是说 SDAP(S)是在“SIDD Medium + SIDD validation + SIDD benchmark + DND benchmark”合并成的数据集上训1个模型，在3个测试集上测。

请问具体上怎么实操的呢？

**Comment by p1y2z3** [comment]
针对SDAP(S)
SIDD val和benchmark的训练集是“SIDD Medium + SIDD validation + SIDD benchmark”
DND benchmark的训练集是“SIDD Medium + DND benchmark”

**Comment by YiwenShan** [comment]
好的，谢谢您。

**Comment by YiwenShan** [comment]
请问作者：
sdap(s)是在“SIDD Medium + SIDD validation + SIDD benchmark”上从头开始训，还是先在SIDD Medium上训，再在SIDD validation + SIDD benchmark上微调呢？

**Comment by p1y2z3** [comment]
从头开始训的
不过两种方法效果应该不会差太多
